
name: Check compile GL

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows (mingw32), os: windows-latest, shell: 'msys2 {0}', msystem: mingw32, msys-env: mingw-w64-i686 }
        - { name: Windows (mingw64), os: windows-latest, shell: 'msys2 {0}', msystem: mingw64, msys-env: mingw-w64-x86_64 }
        - { name: Linux,             os: ubuntu-latest,  shell: bash }
        - { name: MacOS,             os: macos-latest,   shell: bash }
        test-dirs: [examples_pico_gfx]
    steps:
      - name: Set up MSYS2
        if: matrix.platform.shell == 'msys2 {0}'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.platform.msystem }}
          install: >-
            ${{ matrix.platform.msys-env }}-clang
            make
      - name: Setup Linux dependencies
        if: runner.os == 'Linux'
        run: |
             sudo apt-get update
             sudo apt-get install libsdl2-dev
      - name: Setup MinGW64 Dependences
        if: runner.os == 'Windows' && matrix.platform.msystem == 'mingw64'
        run: |
             pacman --noconfirm -S mingw-w64-x86_64-pkg-config
             pacman --noconfirm -S mingw-w64-x86_64-SDL2
      - name: Setup MinGW32 Dependences
        if: runner.os == 'Windows' && matrix.platform.msystem == 'mingw32'
        run: |
             pacman --noconfirm -S mingw-w64-i686-pkg-config
             pacman --noconfirm -S mingw-w64-i686-SDL2
      - name: Setup MacOS Dependences
        if: runner.os == 'MacOS'
        run: |
             brew install sdl2
      - uses: actions/checkout@v2
      - name: Build and run examples
        run: |
             make clean
             make all
        working-directory: ${{ matrix.test-dirs }}

