#include "gamestate.h"
#include "init.h"
#include <tonc.h>

// This file is autogenerated from the file in the graphics folder
#include "metr.h"

OBJ_ATTR obj_buffer[128];
OBJ_AFFINE *obj_aff_buffer = (OBJ_AFFINE *)obj_buffer;

void load_sprite(void) {
  // Load tiles and palette of sprite into video and palete RAM. Note that
  // regular memcpy() won't work. To write to VRAM, it is required to write in
  // units of 16 or 32 bytes. memcpy() doesn't guarantee the size of the
  // writes, but mempcy32() always writes in chunks of 32 bytes.
  memcpy32(&tile_mem[4][0], metrTiles, metrTilesLen / 4);
  memcpy32(pal_obj_mem, metrPal, metrPalLen / 4);

  oam_init(obj_buffer, 128);

  OBJ_ATTR *metr = &obj_buffer[0];
  obj_set_attr(metr,
               ATTR0_SQUARE,          // Square, regular sprite
               ATTR1_SIZE_64,         // 64x64 pixels,
               ATTR2_PALBANK(0) | 0); // palette index 0, tile index 0

  // Set position
  obj_set_pos(metr, 176, 96);

  oam_copy(oam_mem, obj_buffer, 1); // Update first OAM object
}

int main(void) {
  init_system();
  gamestate_set(TITLE);
  while (1) {
    gamestate_draw();
    gamestate_update();
    VBlankIntrWait();
  }
}
